from bibgrafo.grafo_lista_adj_nao_dir import GrafoListaAdjacenciaNaoDirecionado
from meu_grafo_matriz_adj_dir import MeuGrafo

g8 = MeuGrafo()
g8.adiciona_vertice("A")
g8.adiciona_vertice("B")
g8.adiciona_vertice("C")
g8.adiciona_vertice("D")
g8.adiciona_vertice("E")
g8.adiciona_vertice("F")
g8.adiciona_vertice("G")
g8.adiciona_vertice("H")
g8.adiciona_vertice("I")

g8.adiciona_aresta('1', 'A', 'B')
g8.adiciona_aresta('2', 'A', 'C')
g8.adiciona_aresta('3', 'B', 'C')
g8.adiciona_aresta('4', 'C', 'D')
g8.adiciona_aresta('5', 'D', 'E')
g8.adiciona_aresta('6', 'E', 'F')
g8.adiciona_aresta('7', 'F', 'G')
g8.adiciona_aresta('8', 'G', 'H')
g8.adiciona_aresta('9', 'H', 'I')
g8.adiciona_aresta('10', 'I', 'A')

'''g_6 = MeuGrafo()
g_6.adiciona_vertice("A")
g_6.adiciona_vertice("B")
g_6.adiciona_vertice("C")
g_6.adiciona_vertice("D")
g_6.adiciona_vertice("E")
g_6.adiciona_vertice("F")
g_6.adiciona_vertice("G")
g_6.adiciona_aresta("a1", "A", "B")
g_6.adiciona_aresta("a2", "B", "C")
g_6.adiciona_aresta("a3", "C", "D")
g_6.adiciona_aresta("a4", "D", "E")
g_6.adiciona_aresta("a5", "E", "F")
g_6.adiciona_aresta("a6", "F", "G")
g_6.adiciona_aresta("a7", "G", "E")

g_4 = MeuGrafo()
g_4.adiciona_vertice("A")
g_4.adiciona_vertice("B")
g_4.adiciona_vertice("C")
g_4.adiciona_vertice("D")
g_4.adiciona_aresta("a1", "A", "B")
g_4.adiciona_aresta("a2", "B", "C")
g_4.adiciona_aresta("a3", "A", "D")

grafo = MeuGrafo()
grafo.adiciona_vertice("J")
grafo.adiciona_vertice("C")
grafo.adiciona_vertice("E")
grafo.adiciona_vertice("P")
grafo.adiciona_vertice("M")
grafo.adiciona_vertice("T")
grafo.adiciona_vertice("Z")
'''


print(g8.warshall())

